### PR TITLE
Wikilist Window: make colors configurable by palette

### PR DESCRIPTION
**Pull request by BurningTreeC**

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @BurningTreeC

**Comment by BurningTreeC** [comment]
@Jermolene , do you want me to change something in order to merge this?

**Comment by BurningTreeC** [comment]
This is related to #4515 which adds the colors to the Vanilla palette

**Comment by Jermolene** [comment]
Sorry @BurningTreeC I evidently got interrupted between thanking you and merging :smile:

**Pull request merged**
