### PR TITLE
Working version of the copy template functionality for TiddlyDesktop

### PR DESCRIPTION
**Pull request by mklauber**
Adds a dropdown and a button to the TiddlyDesktop Toolbar.  When the button is clicked the selected template is copied to the file location chosen by the user, then the new copy is added to the list and opened.

image

The various templates can be controlled via the settings tiddler.
image

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @mklauber I was just starting to look at this and #86, do you plan to re-submit them?

**Comment by mklauber** [comment]
I closed this one because when I attempted to compile it after merging master, I wasn't seeing the Template interface show up correctly.  I'm open to continuing to work on it, but I need to figure out how to make the add UI work correctly, as the current implementation required the user to understand the wikifile:///... and wikifolder:///... syntax.  

Do you prefer this or the copy wiki style of #86?

**Comment by Jermolene** [comment]
I think this and #86 meet somewhat different needs, and so both make sense. I agree that the UI might need a bit of work but the general idea seems sound.

**Comment by mklauber** [comment]
Sounds good. I'll work on getting these up this week.

**Comment by Jermolene** [comment]
Great, thanks @mklauber

**Comment by mklauber** [comment]
Should be good now!  Comes with built in templates of empty, and empty prerelease.  Also includes the functionality to copy individual wikis.

**Comment by Jermolene** [comment]
Thanks @mklauber

**Pull request merged**
