### PR TITLE
Fix problem with convertFileUrlToPath() on Windows

### PR DESCRIPTION
**Pull request by BramChen**

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @BramChen thanks for this, much appreciated. I didn't realise you were following the TiddlyDesktop development, that's great.

**Comment by Jermolene** [comment]
Looking at the patch, maybe it would be more elegant to use `path.sep`?

http://nodejs.org/api/path.html#path_path_sep

**Comment by BramChen** [comment]
Hi @Jermolene This PR should be closed.

It's explicitly out of date, and the ploblem seem to be fixed on commit [89d44db](https://github.com/Jermolene/TiddlyDesktop/commit/89d44dbc1b95d76ad9c6922f083671fd034c1bfc).

**Comment by Jermolene** [comment]
Thanks @BramChen

**Pull request closed without merging**
